// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/alexferl/zerohttp-example/models"
	mock "github.com/stretchr/testify/mock"

	store "github.com/alexferl/zerohttp-example/store"
)

// MockUserStore is an autogenerated mock type for the UserStore type
type MockUserStore struct {
	mock.Mock
}

type MockUserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStore) EXPECT() *MockUserStore_Expecter {
	return &MockUserStore_Expecter{mock: &_m.Mock}
}

// GetAllUsers provides a mock function with given fields: ctx, filter
func (_m *MockUserStore) GetAllUsers(ctx context.Context, filter store.UserFilter) ([]*models.User, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []*models.User
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, store.UserFilter) ([]*models.User, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.UserFilter) []*models.User); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.UserFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, store.UserFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserStore_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockUserStore_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - filter store.UserFilter
func (_e *MockUserStore_Expecter) GetAllUsers(ctx interface{}, filter interface{}) *MockUserStore_GetAllUsers_Call {
	return &MockUserStore_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx, filter)}
}

func (_c *MockUserStore_GetAllUsers_Call) Run(run func(ctx context.Context, filter store.UserFilter)) *MockUserStore_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.UserFilter))
	})
	return _c
}

func (_c *MockUserStore_GetAllUsers_Call) Return(_a0 []*models.User, _a1 int, _a2 error) *MockUserStore_GetAllUsers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserStore_GetAllUsers_Call) RunAndReturn(run func(context.Context, store.UserFilter) ([]*models.User, int, error)) *MockUserStore_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *MockUserStore) GetUser(ctx context.Context, id string) (*models.User, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *models.User
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserStore_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserStore_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserStore_Expecter) GetUser(ctx interface{}, id interface{}) *MockUserStore_GetUser_Call {
	return &MockUserStore_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUserStore_GetUser_Call) Run(run func(ctx context.Context, id string)) *MockUserStore_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserStore_GetUser_Call) Return(_a0 *models.User, _a1 bool, _a2 error) *MockUserStore_GetUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserStore_GetUser_Call) RunAndReturn(run func(context.Context, string) (*models.User, bool, error)) *MockUserStore_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserStore) GetUserByEmail(ctx context.Context, email string) (*models.User, bool, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *models.User
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, bool, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, email)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserStore_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUserStore_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserStore_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockUserStore_GetUserByEmail_Call {
	return &MockUserStore_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUserStore_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserStore_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserStore_GetUserByEmail_Call) Return(_a0 *models.User, _a1 bool, _a2 error) *MockUserStore_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserStore_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*models.User, bool, error)) *MockUserStore_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function with given fields: ctx, u
func (_m *MockUserStore) SaveUser(ctx context.Context, u *models.User) error {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserStore_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockUserStore_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - u *models.User
func (_e *MockUserStore_Expecter) SaveUser(ctx interface{}, u interface{}) *MockUserStore_SaveUser_Call {
	return &MockUserStore_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, u)}
}

func (_c *MockUserStore_SaveUser_Call) Run(run func(ctx context.Context, u *models.User)) *MockUserStore_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockUserStore_SaveUser_Call) Return(_a0 error) *MockUserStore_SaveUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserStore_SaveUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *MockUserStore_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserStore creates a new instance of MockUserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStore {
	mock := &MockUserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
