// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/alexferl/zerohttp-example/models"
	mock "github.com/stretchr/testify/mock"

	store "github.com/alexferl/zerohttp-example/store"
)

// MockOrderStore is an autogenerated mock type for the OrderStore type
type MockOrderStore struct {
	mock.Mock
}

type MockOrderStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderStore) EXPECT() *MockOrderStore_Expecter {
	return &MockOrderStore_Expecter{mock: &_m.Mock}
}

// GetAllOrders provides a mock function with given fields: ctx, filter
func (_m *MockOrderStore) GetAllOrders(ctx context.Context, filter store.AllOrdersFilter) ([]*models.Order, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllOrders")
	}

	var r0 []*models.Order
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, store.AllOrdersFilter) ([]*models.Order, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.AllOrdersFilter) []*models.Order); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.AllOrdersFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, store.AllOrdersFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockOrderStore_GetAllOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllOrders'
type MockOrderStore_GetAllOrders_Call struct {
	*mock.Call
}

// GetAllOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - filter store.AllOrdersFilter
func (_e *MockOrderStore_Expecter) GetAllOrders(ctx interface{}, filter interface{}) *MockOrderStore_GetAllOrders_Call {
	return &MockOrderStore_GetAllOrders_Call{Call: _e.mock.On("GetAllOrders", ctx, filter)}
}

func (_c *MockOrderStore_GetAllOrders_Call) Run(run func(ctx context.Context, filter store.AllOrdersFilter)) *MockOrderStore_GetAllOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.AllOrdersFilter))
	})
	return _c
}

func (_c *MockOrderStore_GetAllOrders_Call) Return(_a0 []*models.Order, _a1 int, _a2 error) *MockOrderStore_GetAllOrders_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockOrderStore_GetAllOrders_Call) RunAndReturn(run func(context.Context, store.AllOrdersFilter) ([]*models.Order, int, error)) *MockOrderStore_GetAllOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *MockOrderStore) GetOrder(ctx context.Context, id string) (*models.Order, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *models.Order
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Order, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockOrderStore_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderStore_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrderStore_Expecter) GetOrder(ctx interface{}, id interface{}) *MockOrderStore_GetOrder_Call {
	return &MockOrderStore_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *MockOrderStore_GetOrder_Call) Run(run func(ctx context.Context, id string)) *MockOrderStore_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrderStore_GetOrder_Call) Return(_a0 *models.Order, _a1 bool, _a2 error) *MockOrderStore_GetOrder_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockOrderStore_GetOrder_Call) RunAndReturn(run func(context.Context, string) (*models.Order, bool, error)) *MockOrderStore_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrdersByUser provides a mock function with given fields: ctx, filter
func (_m *MockOrderStore) GetOrdersByUser(ctx context.Context, filter store.OrderFilter) ([]*models.Order, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByUser")
	}

	var r0 []*models.Order
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, store.OrderFilter) ([]*models.Order, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.OrderFilter) []*models.Order); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.OrderFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, store.OrderFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockOrderStore_GetOrdersByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrdersByUser'
type MockOrderStore_GetOrdersByUser_Call struct {
	*mock.Call
}

// GetOrdersByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - filter store.OrderFilter
func (_e *MockOrderStore_Expecter) GetOrdersByUser(ctx interface{}, filter interface{}) *MockOrderStore_GetOrdersByUser_Call {
	return &MockOrderStore_GetOrdersByUser_Call{Call: _e.mock.On("GetOrdersByUser", ctx, filter)}
}

func (_c *MockOrderStore_GetOrdersByUser_Call) Run(run func(ctx context.Context, filter store.OrderFilter)) *MockOrderStore_GetOrdersByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.OrderFilter))
	})
	return _c
}

func (_c *MockOrderStore_GetOrdersByUser_Call) Return(_a0 []*models.Order, _a1 int, _a2 error) *MockOrderStore_GetOrdersByUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockOrderStore_GetOrdersByUser_Call) RunAndReturn(run func(context.Context, store.OrderFilter) ([]*models.Order, int, error)) *MockOrderStore_GetOrdersByUser_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrder provides a mock function with given fields: ctx, o
func (_m *MockOrderStore) SaveOrder(ctx context.Context, o *models.Order) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderStore_SaveOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrder'
type MockOrderStore_SaveOrder_Call struct {
	*mock.Call
}

// SaveOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - o *models.Order
func (_e *MockOrderStore_Expecter) SaveOrder(ctx interface{}, o interface{}) *MockOrderStore_SaveOrder_Call {
	return &MockOrderStore_SaveOrder_Call{Call: _e.mock.On("SaveOrder", ctx, o)}
}

func (_c *MockOrderStore_SaveOrder_Call) Run(run func(ctx context.Context, o *models.Order)) *MockOrderStore_SaveOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Order))
	})
	return _c
}

func (_c *MockOrderStore_SaveOrder_Call) Return(_a0 error) *MockOrderStore_SaveOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderStore_SaveOrder_Call) RunAndReturn(run func(context.Context, *models.Order) error) *MockOrderStore_SaveOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderStore creates a new instance of MockOrderStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderStore {
	mock := &MockOrderStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
