// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/alexferl/zerohttp-example/models"
	mock "github.com/stretchr/testify/mock"

	store "github.com/alexferl/zerohttp-example/store"
)

// MockRecordStore is an autogenerated mock type for the RecordStore type
type MockRecordStore struct {
	mock.Mock
}

type MockRecordStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecordStore) EXPECT() *MockRecordStore_Expecter {
	return &MockRecordStore_Expecter{mock: &_m.Mock}
}

// DecrementStock provides a mock function with given fields: ctx, id, quantity
func (_m *MockRecordStore) DecrementStock(ctx context.Context, id string, quantity int) (bool, error) {
	ret := _m.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for DecrementStock")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (bool, error)); ok {
		return rf(ctx, id, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) bool); ok {
		r0 = rf(ctx, id, quantity)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, id, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRecordStore_DecrementStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementStock'
type MockRecordStore_DecrementStock_Call struct {
	*mock.Call
}

// DecrementStock is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - quantity int
func (_e *MockRecordStore_Expecter) DecrementStock(ctx interface{}, id interface{}, quantity interface{}) *MockRecordStore_DecrementStock_Call {
	return &MockRecordStore_DecrementStock_Call{Call: _e.mock.On("DecrementStock", ctx, id, quantity)}
}

func (_c *MockRecordStore_DecrementStock_Call) Run(run func(ctx context.Context, id string, quantity int)) *MockRecordStore_DecrementStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockRecordStore_DecrementStock_Call) Return(_a0 bool, _a1 error) *MockRecordStore_DecrementStock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRecordStore_DecrementStock_Call) RunAndReturn(run func(context.Context, string, int) (bool, error)) *MockRecordStore_DecrementStock_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllRecords provides a mock function with given fields: ctx
func (_m *MockRecordStore) GetAllRecords(ctx context.Context) ([]*models.Record, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRecords")
	}

	var r0 []*models.Record
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Record, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Record); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Record)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRecordStore_GetAllRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllRecords'
type MockRecordStore_GetAllRecords_Call struct {
	*mock.Call
}

// GetAllRecords is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRecordStore_Expecter) GetAllRecords(ctx interface{}) *MockRecordStore_GetAllRecords_Call {
	return &MockRecordStore_GetAllRecords_Call{Call: _e.mock.On("GetAllRecords", ctx)}
}

func (_c *MockRecordStore_GetAllRecords_Call) Run(run func(ctx context.Context)) *MockRecordStore_GetAllRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRecordStore_GetAllRecords_Call) Return(_a0 []*models.Record, _a1 error) *MockRecordStore_GetAllRecords_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRecordStore_GetAllRecords_Call) RunAndReturn(run func(context.Context) ([]*models.Record, error)) *MockRecordStore_GetAllRecords_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilteredRecords provides a mock function with given fields: ctx, filter
func (_m *MockRecordStore) GetFilteredRecords(ctx context.Context, filter store.RecordFilter) ([]*models.Record, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetFilteredRecords")
	}

	var r0 []*models.Record
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, store.RecordFilter) ([]*models.Record, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.RecordFilter) []*models.Record); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Record)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.RecordFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, store.RecordFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRecordStore_GetFilteredRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilteredRecords'
type MockRecordStore_GetFilteredRecords_Call struct {
	*mock.Call
}

// GetFilteredRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - filter store.RecordFilter
func (_e *MockRecordStore_Expecter) GetFilteredRecords(ctx interface{}, filter interface{}) *MockRecordStore_GetFilteredRecords_Call {
	return &MockRecordStore_GetFilteredRecords_Call{Call: _e.mock.On("GetFilteredRecords", ctx, filter)}
}

func (_c *MockRecordStore_GetFilteredRecords_Call) Run(run func(ctx context.Context, filter store.RecordFilter)) *MockRecordStore_GetFilteredRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.RecordFilter))
	})
	return _c
}

func (_c *MockRecordStore_GetFilteredRecords_Call) Return(_a0 []*models.Record, _a1 int, _a2 error) *MockRecordStore_GetFilteredRecords_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRecordStore_GetFilteredRecords_Call) RunAndReturn(run func(context.Context, store.RecordFilter) ([]*models.Record, int, error)) *MockRecordStore_GetFilteredRecords_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecord provides a mock function with given fields: ctx, id
func (_m *MockRecordStore) GetRecord(ctx context.Context, id string) (*models.Record, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRecord")
	}

	var r0 *models.Record
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Record, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Record); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Record)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRecordStore_GetRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecord'
type MockRecordStore_GetRecord_Call struct {
	*mock.Call
}

// GetRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRecordStore_Expecter) GetRecord(ctx interface{}, id interface{}) *MockRecordStore_GetRecord_Call {
	return &MockRecordStore_GetRecord_Call{Call: _e.mock.On("GetRecord", ctx, id)}
}

func (_c *MockRecordStore_GetRecord_Call) Run(run func(ctx context.Context, id string)) *MockRecordStore_GetRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRecordStore_GetRecord_Call) Return(_a0 *models.Record, _a1 bool, _a2 error) *MockRecordStore_GetRecord_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRecordStore_GetRecord_Call) RunAndReturn(run func(context.Context, string) (*models.Record, bool, error)) *MockRecordStore_GetRecord_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRecord provides a mock function with given fields: ctx, r
func (_m *MockRecordStore) SaveRecord(ctx context.Context, r *models.Record) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for SaveRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Record) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRecordStore_SaveRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRecord'
type MockRecordStore_SaveRecord_Call struct {
	*mock.Call
}

// SaveRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - r *models.Record
func (_e *MockRecordStore_Expecter) SaveRecord(ctx interface{}, r interface{}) *MockRecordStore_SaveRecord_Call {
	return &MockRecordStore_SaveRecord_Call{Call: _e.mock.On("SaveRecord", ctx, r)}
}

func (_c *MockRecordStore_SaveRecord_Call) Run(run func(ctx context.Context, r *models.Record)) *MockRecordStore_SaveRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Record))
	})
	return _c
}

func (_c *MockRecordStore_SaveRecord_Call) Return(_a0 error) *MockRecordStore_SaveRecord_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRecordStore_SaveRecord_Call) RunAndReturn(run func(context.Context, *models.Record) error) *MockRecordStore_SaveRecord_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRecordStore creates a new instance of MockRecordStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecordStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecordStore {
	mock := &MockRecordStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
