// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/alexferl/zerohttp-example/models"
	mock "github.com/stretchr/testify/mock"

	store "github.com/alexferl/zerohttp-example/store"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// DecrementStock provides a mock function with given fields: ctx, id, quantity
func (_m *MockStore) DecrementStock(ctx context.Context, id string, quantity int) (bool, error) {
	ret := _m.Called(ctx, id, quantity)

	if len(ret) == 0 {
		panic("no return value specified for DecrementStock")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (bool, error)); ok {
		return rf(ctx, id, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) bool); ok {
		r0 = rf(ctx, id, quantity)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, id, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_DecrementStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementStock'
type MockStore_DecrementStock_Call struct {
	*mock.Call
}

// DecrementStock is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - quantity int
func (_e *MockStore_Expecter) DecrementStock(ctx interface{}, id interface{}, quantity interface{}) *MockStore_DecrementStock_Call {
	return &MockStore_DecrementStock_Call{Call: _e.mock.On("DecrementStock", ctx, id, quantity)}
}

func (_c *MockStore_DecrementStock_Call) Run(run func(ctx context.Context, id string, quantity int)) *MockStore_DecrementStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockStore_DecrementStock_Call) Return(_a0 bool, _a1 error) *MockStore_DecrementStock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_DecrementStock_Call) RunAndReturn(run func(context.Context, string, int) (bool, error)) *MockStore_DecrementStock_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllOrders provides a mock function with given fields: ctx, filter
func (_m *MockStore) GetAllOrders(ctx context.Context, filter store.AllOrdersFilter) ([]*models.Order, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllOrders")
	}

	var r0 []*models.Order
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, store.AllOrdersFilter) ([]*models.Order, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.AllOrdersFilter) []*models.Order); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.AllOrdersFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, store.AllOrdersFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStore_GetAllOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllOrders'
type MockStore_GetAllOrders_Call struct {
	*mock.Call
}

// GetAllOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - filter store.AllOrdersFilter
func (_e *MockStore_Expecter) GetAllOrders(ctx interface{}, filter interface{}) *MockStore_GetAllOrders_Call {
	return &MockStore_GetAllOrders_Call{Call: _e.mock.On("GetAllOrders", ctx, filter)}
}

func (_c *MockStore_GetAllOrders_Call) Run(run func(ctx context.Context, filter store.AllOrdersFilter)) *MockStore_GetAllOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.AllOrdersFilter))
	})
	return _c
}

func (_c *MockStore_GetAllOrders_Call) Return(_a0 []*models.Order, _a1 int, _a2 error) *MockStore_GetAllOrders_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStore_GetAllOrders_Call) RunAndReturn(run func(context.Context, store.AllOrdersFilter) ([]*models.Order, int, error)) *MockStore_GetAllOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllRecords provides a mock function with given fields: ctx
func (_m *MockStore) GetAllRecords(ctx context.Context) ([]*models.Record, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRecords")
	}

	var r0 []*models.Record
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Record, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Record); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Record)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetAllRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllRecords'
type MockStore_GetAllRecords_Call struct {
	*mock.Call
}

// GetAllRecords is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) GetAllRecords(ctx interface{}) *MockStore_GetAllRecords_Call {
	return &MockStore_GetAllRecords_Call{Call: _e.mock.On("GetAllRecords", ctx)}
}

func (_c *MockStore_GetAllRecords_Call) Run(run func(ctx context.Context)) *MockStore_GetAllRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_GetAllRecords_Call) Return(_a0 []*models.Record, _a1 error) *MockStore_GetAllRecords_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetAllRecords_Call) RunAndReturn(run func(context.Context) ([]*models.Record, error)) *MockStore_GetAllRecords_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function with given fields: ctx, filter
func (_m *MockStore) GetAllUsers(ctx context.Context, filter store.UserFilter) ([]*models.User, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []*models.User
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, store.UserFilter) ([]*models.User, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.UserFilter) []*models.User); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.UserFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, store.UserFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStore_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockStore_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - filter store.UserFilter
func (_e *MockStore_Expecter) GetAllUsers(ctx interface{}, filter interface{}) *MockStore_GetAllUsers_Call {
	return &MockStore_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx, filter)}
}

func (_c *MockStore_GetAllUsers_Call) Run(run func(ctx context.Context, filter store.UserFilter)) *MockStore_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.UserFilter))
	})
	return _c
}

func (_c *MockStore_GetAllUsers_Call) Return(_a0 []*models.User, _a1 int, _a2 error) *MockStore_GetAllUsers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStore_GetAllUsers_Call) RunAndReturn(run func(context.Context, store.UserFilter) ([]*models.User, int, error)) *MockStore_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilteredRecords provides a mock function with given fields: ctx, filter
func (_m *MockStore) GetFilteredRecords(ctx context.Context, filter store.RecordFilter) ([]*models.Record, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetFilteredRecords")
	}

	var r0 []*models.Record
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, store.RecordFilter) ([]*models.Record, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.RecordFilter) []*models.Record); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Record)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.RecordFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, store.RecordFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStore_GetFilteredRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilteredRecords'
type MockStore_GetFilteredRecords_Call struct {
	*mock.Call
}

// GetFilteredRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - filter store.RecordFilter
func (_e *MockStore_Expecter) GetFilteredRecords(ctx interface{}, filter interface{}) *MockStore_GetFilteredRecords_Call {
	return &MockStore_GetFilteredRecords_Call{Call: _e.mock.On("GetFilteredRecords", ctx, filter)}
}

func (_c *MockStore_GetFilteredRecords_Call) Run(run func(ctx context.Context, filter store.RecordFilter)) *MockStore_GetFilteredRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.RecordFilter))
	})
	return _c
}

func (_c *MockStore_GetFilteredRecords_Call) Return(_a0 []*models.Record, _a1 int, _a2 error) *MockStore_GetFilteredRecords_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStore_GetFilteredRecords_Call) RunAndReturn(run func(context.Context, store.RecordFilter) ([]*models.Record, int, error)) *MockStore_GetFilteredRecords_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *MockStore) GetOrder(ctx context.Context, id string) (*models.Order, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *models.Order
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Order, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStore_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockStore_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockStore_Expecter) GetOrder(ctx interface{}, id interface{}) *MockStore_GetOrder_Call {
	return &MockStore_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *MockStore_GetOrder_Call) Run(run func(ctx context.Context, id string)) *MockStore_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_GetOrder_Call) Return(_a0 *models.Order, _a1 bool, _a2 error) *MockStore_GetOrder_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStore_GetOrder_Call) RunAndReturn(run func(context.Context, string) (*models.Order, bool, error)) *MockStore_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrdersByUser provides a mock function with given fields: ctx, filter
func (_m *MockStore) GetOrdersByUser(ctx context.Context, filter store.OrderFilter) ([]*models.Order, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByUser")
	}

	var r0 []*models.Order
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, store.OrderFilter) ([]*models.Order, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.OrderFilter) []*models.Order); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.OrderFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, store.OrderFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStore_GetOrdersByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrdersByUser'
type MockStore_GetOrdersByUser_Call struct {
	*mock.Call
}

// GetOrdersByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - filter store.OrderFilter
func (_e *MockStore_Expecter) GetOrdersByUser(ctx interface{}, filter interface{}) *MockStore_GetOrdersByUser_Call {
	return &MockStore_GetOrdersByUser_Call{Call: _e.mock.On("GetOrdersByUser", ctx, filter)}
}

func (_c *MockStore_GetOrdersByUser_Call) Run(run func(ctx context.Context, filter store.OrderFilter)) *MockStore_GetOrdersByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.OrderFilter))
	})
	return _c
}

func (_c *MockStore_GetOrdersByUser_Call) Return(_a0 []*models.Order, _a1 int, _a2 error) *MockStore_GetOrdersByUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStore_GetOrdersByUser_Call) RunAndReturn(run func(context.Context, store.OrderFilter) ([]*models.Order, int, error)) *MockStore_GetOrdersByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecord provides a mock function with given fields: ctx, id
func (_m *MockStore) GetRecord(ctx context.Context, id string) (*models.Record, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRecord")
	}

	var r0 *models.Record
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Record, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Record); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Record)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStore_GetRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecord'
type MockStore_GetRecord_Call struct {
	*mock.Call
}

// GetRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockStore_Expecter) GetRecord(ctx interface{}, id interface{}) *MockStore_GetRecord_Call {
	return &MockStore_GetRecord_Call{Call: _e.mock.On("GetRecord", ctx, id)}
}

func (_c *MockStore_GetRecord_Call) Run(run func(ctx context.Context, id string)) *MockStore_GetRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_GetRecord_Call) Return(_a0 *models.Record, _a1 bool, _a2 error) *MockStore_GetRecord_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStore_GetRecord_Call) RunAndReturn(run func(context.Context, string) (*models.Record, bool, error)) *MockStore_GetRecord_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *MockStore) GetUser(ctx context.Context, id string) (*models.User, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *models.User
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStore_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockStore_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockStore_Expecter) GetUser(ctx interface{}, id interface{}) *MockStore_GetUser_Call {
	return &MockStore_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockStore_GetUser_Call) Run(run func(ctx context.Context, id string)) *MockStore_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_GetUser_Call) Return(_a0 *models.User, _a1 bool, _a2 error) *MockStore_GetUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStore_GetUser_Call) RunAndReturn(run func(context.Context, string) (*models.User, bool, error)) *MockStore_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockStore) GetUserByEmail(ctx context.Context, email string) (*models.User, bool, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *models.User
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, bool, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, email)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStore_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockStore_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockStore_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockStore_GetUserByEmail_Call {
	return &MockStore_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockStore_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockStore_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_GetUserByEmail_Call) Return(_a0 *models.User, _a1 bool, _a2 error) *MockStore_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStore_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*models.User, bool, error)) *MockStore_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrder provides a mock function with given fields: ctx, o
func (_m *MockStore) SaveOrder(ctx context.Context, o *models.Order) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_SaveOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrder'
type MockStore_SaveOrder_Call struct {
	*mock.Call
}

// SaveOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - o *models.Order
func (_e *MockStore_Expecter) SaveOrder(ctx interface{}, o interface{}) *MockStore_SaveOrder_Call {
	return &MockStore_SaveOrder_Call{Call: _e.mock.On("SaveOrder", ctx, o)}
}

func (_c *MockStore_SaveOrder_Call) Run(run func(ctx context.Context, o *models.Order)) *MockStore_SaveOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Order))
	})
	return _c
}

func (_c *MockStore_SaveOrder_Call) Return(_a0 error) *MockStore_SaveOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_SaveOrder_Call) RunAndReturn(run func(context.Context, *models.Order) error) *MockStore_SaveOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRecord provides a mock function with given fields: ctx, r
func (_m *MockStore) SaveRecord(ctx context.Context, r *models.Record) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for SaveRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Record) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_SaveRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRecord'
type MockStore_SaveRecord_Call struct {
	*mock.Call
}

// SaveRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - r *models.Record
func (_e *MockStore_Expecter) SaveRecord(ctx interface{}, r interface{}) *MockStore_SaveRecord_Call {
	return &MockStore_SaveRecord_Call{Call: _e.mock.On("SaveRecord", ctx, r)}
}

func (_c *MockStore_SaveRecord_Call) Run(run func(ctx context.Context, r *models.Record)) *MockStore_SaveRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Record))
	})
	return _c
}

func (_c *MockStore_SaveRecord_Call) Return(_a0 error) *MockStore_SaveRecord_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_SaveRecord_Call) RunAndReturn(run func(context.Context, *models.Record) error) *MockStore_SaveRecord_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function with given fields: ctx, u
func (_m *MockStore) SaveUser(ctx context.Context, u *models.User) error {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockStore_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - u *models.User
func (_e *MockStore_Expecter) SaveUser(ctx interface{}, u interface{}) *MockStore_SaveUser_Call {
	return &MockStore_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, u)}
}

func (_c *MockStore_SaveUser_Call) Run(run func(ctx context.Context, u *models.User)) *MockStore_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockStore_SaveUser_Call) Return(_a0 error) *MockStore_SaveUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_SaveUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *MockStore_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
